workflows:
  ios-build:
    name: List Xcode Schemes
    max_build_duration: 10
    environment:
      xcode: latest
    scripts:
      - name: List available schemes
        script: |
          xcodebuild -list -project BabyTracker.xcodeproj
